Minwei
Dashark/dam0888socket pull request #1
Opened 2018-11-21 01:37 UTC by minwei123

2018-12-07 02:29 UTC, Dashark approved these changes

2018-12-07 02:36 UTC, Dashark requested changes
查查json文档

2018-12-07 02:36 UTC, Dashark commented on ZLServer.cpp
> +
这些代码可以直接删除，没用了。

2018-12-07 02:36 UTC, Dashark commented on ZLServer.cpp
> +  int port=jsonToInt(js_["port"]);
json代码应该有方法直接返回数字，用不着自己再转换。查查文档。

2018-12-07 02:36 UTC, Dashark commented on ZLServer.cpp
> +   if(js_["port"]==""){
前面已经转换整数，这儿判断逻辑有问题。

2018-12-07 02:37 UTC, Dashark approved these changes

2018-12-07 03:08 UTC, Dashark requested changes

2018-12-07 03:08 UTC, Dashark commented on Broker.cpp
> +   syslog(LOG_ERR, "loaded Kafka host: %s",host);
使用str_host.c_str()

2018-12-07 03:08 UTC, Dashark commented on Broker.cpp
> +   char* tstr=(char*)str_tstr.data();
使用c_str()

2018-12-07 03:08 UTC, Dashark commented on Broker.cpp
> +RdKafka::Topic* KafkaDefine::kafkaTopic(json js_topic) {
参数：const json &js_topic

2018-12-07 03:08 UTC, Dashark commented on Broker.cpp
> +  char* devs=(char*)str_devs.data();
不需要转换为char*

2018-12-07 03:08 UTC, Dashark commented on Broker.cpp
> +  char* json=(char*)str_json.data();
一样的错误

2018-12-07 03:08 UTC, Dashark commented on Broker.h
>    GKeyFile *keyFile_;
删除

2018-12-07 03:08 UTC, Dashark commented on Device.cpp
> +      char* id=(char*)str_id.data();
不能这样使用

2018-12-07 03:08 UTC, Dashark commented on Device.cpp
> +      char* ip=(char*)str_ip.data();
所有类似代码都不对

2018-12-07 03:08 UTC, Dashark commented on Operation.cpp
> +int jsonToInt2(json j)
应该不需要这样的函数

2018-12-07 03:08 UTC, Dashark commented on Operation.cpp
> +	    char* name=(char*)str_name.data();
不能这样使用

2018-12-07 03:08 UTC, Dashark commented on Operation.h
> +  std::vector<Operation*> create(json operate, const std::string &type);
const json &operate

2018-12-07 03:09 UTC, Dashark approved these changes

2018-12-08 01:00 UTC, minwei123 commented on Operation.cpp
> +int jsonToInt2(json j)
这个函数已经修改掉了

2018-12-08 01:12 UTC, minwei123 commented on ZLServer.cpp
> +   if(js_["port"]==""){
已经转换的字段是port，是int类型，但是，js_[“port”]不是，所以可以做非空判断。

2018-12-08 01:13 UTC, minwei123 commented on Broker.cpp
> +   syslog(LOG_ERR, "loaded Kafka host: %s",host);
已经全部改过来了

2018-12-08 01:13 UTC, minwei123 commented on Broker.cpp
> +   char* tstr=(char*)str_tstr.data();
已经全部改过来了

2018-12-08 01:20 UTC, minwei123 commented on ZLServer.cpp
> +
好的

2018-12-08 01:25 UTC, chacemin commented on ZLServer.cpp
> +
这个代码再设备为空的时候可以打印，便于查错

2018-12-08 01:26 UTC, chacemin commented on ZLServer.cpp
> +  int port=jsonToInt(js_["port"]);
用c++里的库方法转

2018-12-19 08:30 UTC, merged