新修改
Dashark/dam0888socket pull request #2
Opened 2018-12-07 02:48 UTC by minwei123

2018-12-07 03:18 UTC, Dashark requested changes

2018-12-07 03:18 UTC, Dashark commented on Operation.cpp
> +  if(operate=="")
这个比较是什么意思 ？

2018-12-07 03:18 UTC, Dashark commented on Device.cpp
> +      char* ip=(char*)str_ip.data();
不能这样使用

2018-12-08 00:59 UTC, chacemin commented on Operation.cpp
> +  if(operate=="")
这个比较，是用来查看这个，operate之中是否有元素，没有元素，证明没有配置，打印出来。便于查证。

2018-12-08 04:17 UTC, Dashark requested changes

2018-12-08 04:17 UTC, Dashark commented on Operation.cpp
> +  if(operate=="")
查查json文档，判断json为空，直接比较字符串吗？

2018-12-08 04:17 UTC, Dashark commented on ZLServer.cpp
> +  int port=std::stoi(str_port);
直接写
int port = js_["port"].get<int>();

2018-12-08 04:17 UTC, Dashark commented on ZLServer.cpp
>     if(js_["port"]==""){
直接验证转换后的数据，不要再比较json了，而且也不应该直接比较字符串

2018-12-19 08:30 UTC, merged